# Generated by Django 2.1.5 on 2019-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='execution_details',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=20)),
                ('execution_date', models.DateField()),
            ],
        ),
    ]
